export const seriesData = [
  {
    id: "breakingbad",
    titulo: "Breaking Bad",
    categoria: "series",
    imagem: "images/breakingbad.jpeg",
    sinopse: "Um professor de química com câncer se torna um produtor de metanfetamina para garantir o futuro financeiro de sua família.",
    ano: 2008,
    duracao: "5 temporadas",
    diretor: "Vince Gilligan",
    elenco: "Bryan Cranston, Aaron Paul, Anna Gunn",
    imdb: 9.5,
    classificacao: "16+",
    genero: "Crime, Drama, Thriller",
    episodios: 62
  },
  {
    id: "got",
    titulo: "Game of Thrones",
    categoria: "series",
    imagem: "images/gameofthrones.jpeg",
    sinopse: "Nove famílias nobres lutam pelo controle das terras míticas de Westeros, enquanto uma antiga ameaça ressurge.",
    ano: 2011,
    duracao: "8 temporadas",
    diretor: "David Benioff, D.B. Weiss",
    elenco: "Emilia Clarke, Kit Harington, Peter Dinklage",
    imdb: 9.2,
    classificacao: "16+",
    genero: "Ação, Aventura, Drama",
    episodios: 73
  },
  {
    id: "vikings",
    titulo: "Vikings",
    categoria: "series",
    imagem: "images/vikings.jpeg",
    sinopse: "A saga de Ragnar Lothbrok, um dos maiores heróis nórdicos, e suas aventuras ao lado de seus irmãos vikings e sua família.",
    ano: 2013,
    duracao: "6 temporadas",
    diretor: "Michael Hirst",
    elenco: "Travis Fimmel, Katheryn Winnick, Clive Standen",
    imdb: 8.5,
    classificacao: "16+",
    genero: "Ação, Aventura, Drama",
    episodios: 89
  },
  {
    id: "onepiece",
    titulo: "One Piece",
    categoria: "animacoes",
    imagem: "images/onepiece.jpg",
    sinopse: "Siga as aventuras de Monkey D. Luffy e sua tripulação de piratas em busca do maior tesouro do mundo, o One Piece.",
    ano: 1999,
    duracao: "20 temporadas",
    diretor: "Eiichiro Oda",
    elenco: "Mayumi Tanaka, Kazuya Nakai, Akemi Okamura",
    imdb: 9.0,
    classificacao: "14+",
    genero: "Ação, Aventura, Animação",
    episodios: 1144 
  },
  {
    id: "demonslater", 
    titulo: "Demon Slayer",
    categoria: "animacoes",
    imagem: "images/demonslater.jpg", 
    sinopse: "Um jovem se torna um caçador de demônios para vingar sua família e curar sua irmã que foi transformada em um demônio.",
    ano: 2019,
    duracao: "4 temporadas",
    diretor: "Haruo Sotozaki",
    elenco: "Natsuki Hanae, Akari Kito, Hiro Shimono",
    imdb: 8.6,
    classificacao: "14+",
    genero: "Ação, Fantasia Sombria, Animação",
    episodios: 63
  },
  {
    id: "arremessofinal", 
    titulo: "Last Dance - Arremesso final",
    categoria: "filmes",
    imagem: "images/arremessofinal.jpg", 
    sinopse: "Traçando a ascensão dos Chicago Bulls de 1990, liderados por Michael Jordan, uma das dinastias mais notáveis da história do esporte..",
    ano: 2020,
    duracao: "1 Temporada",
    diretor: "Jason Hehir",
    elenco: " Michael Jordan, Phil Jackson, Scottie Pippen",
    imdb: 9.0,
    classificacao: "16+",
    genero: "Drama, Documentário, Biografia, Esporte, História",
    episodios: 10
  },
  {
    id: "apenasumshow", 
    titulo: "Apenas um Show",
    categoria: "animacoes",
    imagem: "images/apenasumshow.jpg", 
    sinopse: "As aventuras diárias e surreais de um duende de gaio-azul e guaxinim que tentam lidar com seus trabalhos mundanos como jardineiros no parque local.",
    ano: 2010,
    duracao: "8 Temporadas",
    diretor: "J.G. Quintel",
    elenco: "J.G. QuintelWilliam SalyersSam Marin",
    imdb: 8.6,
    classificacao: "12+",
    genero: "Animação, Sitcom, Aventura, Comédia",
    episodios: 261
  },
  {
    id: "rickandmorty",
    titulo: "Rick and Morty",
    categoria: "animacoes",
    imagem: "images/rickemorty.webp",
    sinopse: "As aventuras de um cientista alcoólatra e seu neto ingênuo enquanto exploram universos paralelos e situações absurdas.",
    ano: 2013,
    duracao: "6 temporadas",
    diretor: "Justin Roiland, Dan Harmon",
    elenco: "Justin Roiland, Chris Parnell, Spencer Grammer",
    imdb: 9.2,
    classificacao: "16+",
    genero: "Animação, Comédia, Ficção Científica",
    episodios: 61
  },
  {
    id: "supernatural",
    titulo: "Supernatural",
    categoria: "series",
    imagem: "images/sobrenatural.jpeg",
    sinopse: "Dois irmãos caçam monstros, fantasmas, demônios e outras forças sobrenaturais enquanto desvendam segredos sobre sua própria família.",
    ano: 2005,
    duracao: "15 temporadas",
    diretor: "Eric Kripke",
    elenco: "Jared Padalecki, Jensen Ackles, Misha Collins",
    imdb: 8.4,
    classificacao: "16+",
    genero: "Drama, Fantasia, Horror, Mistério",
    episodios: 327
  },
  {
    id: "nossoplaneta",
    titulo: "Nosso Planeta",
    categoria: "filmes",
    imagem: "images/nossoplaneta.jpg",
    sinopse: "Documentário que explora a beleza natural do planeta Terra e os impactos da atividade humana sobre a vida selvagem.",
    ano: 2019,
    duracao: "1 temporada",
    diretor: "Alastair Fothergill",
    elenco: "David Attenborough",
    imdb: 9.3,
    classificacao: "Livre",
    genero: "Documentário, Natureza, Educativo",
    episodios: 8
  },
  {
    id: "guerradovietna",
    titulo: "A Guerra do Vietnã",
    categoria: "filmes",
    imagem: "images/aguerradovietnam.jpg",
    sinopse: "Documentário histórico que detalha os eventos, batalhas e consequências da Guerra do Vietnã.",
    ano: 2017,
    duracao: "10 episódios",
    diretor: "Ken Burns, Lynn Novick",
    elenco: "",
    imdb: 9.0,
    classificacao: "14+",
    genero: "Documentário, História, Guerra",
    episodios: 10
  },
  {
    id: "reacher",
    titulo: "Reacher",
    categoria: "series",
    imagem: "img/series_3082_reacher-poster-easy-resize.com.jpg",
    sinopse: "Jack Reacher, um ex-policial militar, é falsamente acusado de assassinato em uma pequena cidade e se envolve em uma conspiração mortal.",
    ano: 2022,
    duracao: "2 temporadas",
    diretor: "Nick Santora",
    elenco: "Alan Ritchson, Malcolm Goodwin, Willa Fitzgerald",
    imdb: 8.0,
    classificacao: "16+",
    genero: "Ação, Crime, Drama",
    episodios: 16
  },
  {
    id: "contagemregressiva",
    titulo: "Contagem Regressiva",
    categoria: "series",
    imagem: "img/contagem-regressiva.jpg",
    sinopse: "Um drama policial coreano que acompanha um ex-caçador de recompensas que agora trabalha em uma agência governamental para capturar criminosos perigosos.",
    ano: 2024,
    duracao: "1 temporada",
    diretor: "Kwon Young-il",
    elenco: "Kang Ha-neul, Lim Ji-yeon",
    imdb: 7.5,
    classificacao: "16+",
    genero: "Ação, Crime, Drama",
    episodios: 12
  },
  {
    id: "thewalkingdead",
    titulo: "The Walking Dead",
    categoria: "series",
    imagem: "img/thewalking.webp",
    sinopse: "Um grupo de sobreviventes luta para permanecer vivo após um apocalipse zumbi que devastou o mundo.",
    ano: 2010,
    duracao: "11 temporadas",
    diretor: "Frank Darabont",
    elenco: "Andrew Lincoln, Norman Reedus, Melissa McBride",
    imdb: 8.1,
    classificacao: "18+",
    genero: "Drama, Terror, Suspense",
    episodios: 177
  },
  {
    id: "dark",
    titulo: "Dark",
    categoria: "series",
    imagem: "img/dark.png",
    sinopse: "Quatro famílias entrelaçadas descobrem segredos sombrios e uma conspiração de viagem no tempo que atravessa várias gerações.",
    ano: 2017,
    duracao: "3 temporadas",
    diretor: "Baran bo Odar, Jantje Friese",
    elenco: "Louis Hofmann, Karoline Eichhorn, Lisa Vicari",
    imdb: 8.8,
    classificacao: "16+",
    genero: "Drama, Ficção Científica, Mistério",
    episodios: 26
  },
  {
    id: "lacasadepapel",
    titulo: "La Casa de Papel",
    categoria: "series",
    imagem: "img/la casa de papel.jpg",
    sinopse: "Um grupo de assaltantes, liderados pelo enigmático Professor, realiza os maiores assaltos da história da Espanha.",
    ano: 2017,
    duracao: "5 temporadas",
    diretor: "Álex Pina",
    elenco: "Úrsula Corberó, Álvaro Morte, Pedro Alonso",
    imdb: 8.2,
    classificacao: "16+",
    genero: "Ação, Crime, Drama",
    episodios: 41
  },
  {
    id: "thechosen",
    titulo: "The Chosen",
    categoria: "series",
    imagem: "img/thechosen.png",
    sinopse: "A vida e os ensinamentos de Jesus de Nazaré retratados de forma única, através dos olhos das pessoas que o conheceram.",
    ano: 2017,
    duracao: "4 temporadas",
    diretor: "Dallas Jenkins",
    elenco: "Jonathan Roumie, Shahar Isaac, Elizabeth Tabish",
    imdb: 9.2,
    classificacao: "12+",
    genero: "Drama, Histórico, Religião",
    episodios: 32
  }
];