export const seriesData = [
  {
    id: "breakingbad",
    titulo: "Breaking Bad",
    categoria: "series",
    imagem: "images/breakingbad.jpeg",
    sinopse: "Um professor de química com câncer se torna um produtor de metanfetamina para garantir o futuro financeiro de sua família.",
    ano: 2008,
    duracao: "5 temporadas",
    diretor: "Vince Gilligan",
    elenco: "Bryan Cranston, Aaron Paul, Anna Gunn",
    imdb: 9.5,
    classificacao: "16+",
    genero: "Crime, Drama, Thriller",
    episodios: 62
  },
  {
    id: "got",
    titulo: "Game of Thrones",
    categoria: "series",
    imagem: "images/gameofthrones.jpeg",
    sinopse: "Nove famílias nobres lutam pelo controle das terras míticas de Westeros, enquanto uma antiga ameaça ressurge.",
    ano: 2011,
    duracao: "8 temporadas",
    diretor: "David Benioff, D.B. Weiss",
    elenco: "Emilia Clarke, Kit Harington, Peter Dinklage",
    imdb: 9.2,
    classificacao: "16+",
    genero: "Ação, Aventura, Drama",
    episodios: 73
  },
  {
    id: "vikings",
    titulo: "Vikings",
    categoria: "series",
    imagem: "images/vikings.jpeg",
    sinopse: "A saga de Ragnar Lothbrok, um dos maiores heróis nórdicos, e suas aventuras ao lado de seus irmãos vikings e sua família.",
    ano: 2013,
    duracao: "6 temporadas",
    diretor: "Michael Hirst",
    elenco: "Travis Fimmel, Katheryn Winnick, Clive Standen",
    imdb: 8.5,
    classificacao: "16+",
    genero: "Ação, Aventura, Drama",
    episodios: 89
  },
  {
    id: "onepiece",
    titulo: "One Piece",
    categoria: "animacoes",
    imagem: "images/onepiece.jpg",
    sinopse: "Siga as aventuras de Monkey D. Luffy e sua tripulação de piratas em busca do maior tesouro do mundo, o One Piece.",
    ano: 1999,
    duracao: "20 temporadas",
    diretor: "Eiichiro Oda",
    elenco: "Mayumi Tanaka, Kazuya Nakai, Akemi Okamura",
    imdb: 9.0,
    classificacao: "14+",
    genero: "Ação, Aventura, Animação",
    episodios: 1144 
  },
  {
    id: "demonslater", 
    titulo: "Demon Slayer",
    categoria: "animacoes",
    imagem: "images/demonslater.jpg", 
    sinopse: "Um jovem se torna um caçador de demônios para vingar sua família e curar sua irmã que foi transformada em um demônio.",
    ano: 2019,
    duracao: "4 temporadas",
    diretor: "Haruo Sotozaki",
    elenco: "Natsuki Hanae, Akari Kito, Hiro Shimono",
    imdb: 8.6,
    classificacao: "14+",
    genero: "Ação, Fantasia Sombria, Animação",
    episodios: 63
  },
  {
    id: "arremessofinal", 
    titulo: "Last Dance - Arremesso final",
    categoria: "filmes",
    imagem: "images/arremessofinal.jpg", 
    sinopse: "Traçando a ascensão dos Chicago Bulls de 1990, liderados por Michael Jordan, uma das dinastias mais notáveis da história do esporte..",
    ano: 2020,
    duracao: "1 Temporada",
    diretor: "Jason Hehir",
    elenco: " Michael Jordan, Phil Jackson, Scottie Pippen",
    imdb: 9.0,
    classificacao: "16+",
    genero: "Drama, Documentário, Biografia, Esporte, História",
    episodios: 10
  },
  {
    id: "apenasumshow", 
    titulo: "Apenas um Show",
    categoria: "animacoes",
    imagem: "images/apenasumshow.jpg", 
    sinopse: "As aventuras diárias e surreais de um duende de gaio-azul e guaxinim que tentam lidar com seus trabalhos mundanos como jardineiros no parque local.",
    ano: 2010,
    duracao: "8 Temporadas",
    diretor: "J.G. Quintel",
    elenco: "J.G. QuintelWilliam SalyersSam Marin",
    imdb: 8.6,
    classificacao: "12+",
    genero: "Animação, Sitcom, Aventura, Comédia",
    episodios: 261
  },
  {
    id: "rickandmorty",
    titulo: "Rick and Morty",
    categoria: "animacoes",
    imagem: "images/rickemorty.webp",
    sinopse: "As aventuras de um cientista alcoólatra e seu neto ingênuo enquanto exploram universos paralelos e situações absurdas.",
    ano: 2013,
    duracao: "6 temporadas",
    diretor: "Justin Roiland, Dan Harmon",
    elenco: "Justin Roiland, Chris Parnell, Spencer Grammer",
    imdb: 9.2,
    classificacao: "16+",
    genero: "Animação, Comédia, Ficção Científica",
    episodios: 61
  },
  {
    id: "supernatural",
    titulo: "Supernatural",
    categoria: "series",
    imagem: "images/sobrenatural.jpeg",
    sinopse: "Dois irmãos caçam monstros, fantasmas, demônios e outras forças sobrenaturais enquanto desvendam segredos sobre sua própria família.",
    ano: 2005,
    duracao: "15 temporadas",
    diretor: "Eric Kripke",
    elenco: "Jared Padalecki, Jensen Ackles, Misha Collins",
    imdb: 8.4,
    classificacao: "16+",
    genero: "Drama, Fantasia, Horror, Mistério",
    episodios: 327
  },
  {
    id: "nossoplaneta",
    titulo: "Nosso Planeta",
    categoria: "filmes",
    imagem: "images/nossoplaneta.jpg",
    sinopse: "Documentário que explora a beleza natural do planeta Terra e os impactos da atividade humana sobre a vida selvagem.",
    ano: 2019,
    duracao: "1 temporada",
    diretor: "Alastair Fothergill",
    elenco: "David Attenborough",
    imdb: 9.3,
    classificacao: "Livre",
    genero: "Documentário, Natureza, Educativo",
    episodios: 8
  },
  {
    id: "guerradovietna",
    titulo: "A Guerra do Vietnã",
    categoria: "filmes",
    imagem: "images/aguerradovietnam.jpg",
    sinopse: "Documentário histórico que detalha os eventos, batalhas e consequências da Guerra do Vietnã.",
    ano: 2017,
    duracao: "10 episódios",
    diretor: "Ken Burns, Lynn Novick",
    elenco: "",
    imdb: 9.0,
    classificacao: "14+",
    genero: "Documentário, História, Guerra",
    episodios: 10
  },
  {
    id: "reacher",
    titulo: "Reacher",
    categoria: "series",
    imagem: "img/series_3082_reacher-poster-easy-resize.com.jpg",
    sinopse: "Jack Reacher, um ex-policial militar, é falsamente acusado de assassinato em uma pequena cidade e se envolve em uma conspiração mortal.",
    ano: 2022,
    duracao: "2 temporadas",
    diretor: "Nick Santora",
    elenco: "Alan Ritchson, Malcolm Goodwin, Willa Fitzgerald",
    imdb: 8.0,
    classificacao: "16+",
    genero: "Ação, Crime, Drama",
    episodios: 16
  },
  {
    id: "contagemregressiva",
    titulo: "Contagem Regressiva",
    categoria: "series",
    imagem: "img/contagem-regressiva.jpg",
    sinopse: "Um drama policial coreano que acompanha um ex-caçador de recompensas que agora trabalha em uma agência governamental para capturar criminosos perigosos.",
    ano: 2024,
    duracao: "1 temporada",
    diretor: "Kwon Young-il",
    elenco: "Kang Ha-neul, Lim Ji-yeon",
    imdb: 7.5,
    classificacao: "16+",
    genero: "Ação, Crime, Drama",
    episodios: 12
  },
  {
    id: "thewalkingdead",
    titulo: "The Walking Dead",
    categoria: "series",
    imagem: "img/thewalking.webp",
    sinopse: "Um grupo de sobreviventes luta para permanecer vivo após um apocalipse zumbi que devastou o mundo.",
    ano: 2010,
    duracao: "11 temporadas",
    diretor: "Frank Darabont",
    elenco: "Andrew Lincoln, Norman Reedus, Melissa McBride",
    imdb: 8.1,
    classificacao: "18+",
    genero: "Drama, Terror, Suspense",
    episodios: 177
  },
  {
    id: "dark",
    titulo: "Dark",
    categoria: "series",
    imagem: "img/dark.png",
    sinopse: "Quatro famílias entrelaçadas descobrem segredos sombrios e uma conspiração de viagem no tempo que atravessa várias gerações.",
    ano: 2017,
    duracao: "3 temporadas",
    diretor: "Baran bo Odar, Jantje Friese",
    elenco: "Louis Hofmann, Karoline Eichhorn, Lisa Vicari",
    imdb: 8.8,
    classificacao: "16+",
    genero: "Drama, Ficção Científica, Mistério",
    episodios: 26
  },
  {
    id: "lacasadepapel",
    titulo: "La Casa de Papel",
    categoria: "series",
    imagem: "img/la casa de papel.jpg",
    sinopse: "Um grupo de assaltantes, liderados pelo enigmático Professor, realiza os maiores assaltos da história da Espanha.",
    ano: 2017,
    duracao: "5 temporadas",
    diretor: "Álex Pina",
    elenco: "Úrsula Corberó, Álvaro Morte, Pedro Alonso",
    imdb: 8.2,
    classificacao: "16+",
    genero: "Ação, Crime, Drama",
    episodios: 41
  },
  {
    id: "thechosen",
    titulo: "The Chosen",
    categoria: "series",
    imagem: "img/thechosen.png",
    sinopse: "A vida e os ensinamentos de Jesus de Nazaré retratados de forma única, através dos olhos das pessoas que o conheceram.",
    ano: 2017,
    duracao: "4 temporadas",
    diretor: "Dallas Jenkins",
    elenco: "Jonathan Roumie, Shahar Isaac, Elizabeth Tabish",
    imdb: 9.2,
    classificacao: "12+",
    genero: "Drama, Histórico, Religião",
    episodios: 32
  }
];

export const moviesData = [
  {
    id: "batmandarkknightrises",
    titulo: "Batman: O Cavaleiro das Trevas Ressurge",
    categoria: "filmes",
    imagem: "images/TheDarkKnightRises.jpg",
    sinopse: "Após anos desaparecido, Batman retorna a Gotham para enfrentar a ameaça de Bane, um terrorista que coloca a cidade em colapso.",
    ano: 2012,
    duracao: "2h 44min",
    diretor: "Christopher Nolan",
    elenco: "Christian Bale, Tom Hardy, Anne Hathaway",
    imdb: 8.4,
    classificacao: "12+",
    genero: "Ação, Suspense, Drama",
    episodios: 1
  },
  {
    id: "avengersinfinitywar",
    titulo: "Vingadores: Guerra Infinita",
    categoria: "filmes",
    imagem: "images/Avengers_Infinity_War.jpg",
    sinopse: "Os Vingadores e seus aliados precisam sacrificar tudo para derrotar o poderoso Thanos antes que ele destrua o universo.",
    ano: 2018,
    duracao: "2h 29min",
    diretor: "Anthony Russo, Joe Russo",
    elenco: "Robert Downey Jr., Chris Hemsworth, Chris Evans",
    imdb: 8.4,
    classificacao: "12+",
    genero: "Ação, Aventura, Ficção Científica",
    episodios: 1
  },
  {
    id: "godfather",
    titulo: "O Poderoso Chefão",
    categoria: "filmes",
    imagem: "images/20120876.webp",
    sinopse: "A saga da família Corleone, uma das mais poderosas máfias dos Estados Unidos, e a transição de poder entre gerações.",
    ano: 1972,
    duracao: "2h 55min",
    diretor: "Francis Ford Coppola",
    elenco: "Marlon Brando, Al Pacino, James Caan",
    imdb: 9.2,
    classificacao: "16+",
    genero: "Crime, Drama",
    episodios: 1
  },
  {
    id: "furious7",
    titulo: "Velozes e Furiosos 7",
    categoria: "filmes",
    imagem: "images/Furious_7_poster.jpg",
    sinopse: "Dominic Toretto e sua equipe enfrentam um assassino em busca de vingança, enquanto lidam com missões explosivas ao redor do mundo.",
    ano: 2015,
    duracao: "2h 17min",
    diretor: "James Wan",
    elenco: "Vin Diesel, Paul Walker, Dwayne Johnson",
    imdb: 7.1,
    classificacao: "12+",
    genero: "Ação, Crime, Suspense",
    episodios: 1
  },
  {
    id: "starwars3",
    titulo: "Star Wars: Episódio III – A Vingança dos Sith",
    categoria: "filmes",
    imagem: "images/Star_Wars_Episódio_III_A_Vingança_dos_Sith.jpg",
    sinopse: "Anakin Skywalker cede ao lado sombrio da Força, tornando-se Darth Vader e mudando para sempre o destino da galáxia.",
    ano: 2005,
    duracao: "2h 20min",
    diretor: "George Lucas",
    elenco: "Hayden Christensen, Ewan McGregor, Natalie Portman",
    imdb: 7.6,
    classificacao: "12+",
    genero: "Ação, Aventura, Ficção Científica",
    episodios: 1
  },
  {
    id: "lotrreturnoftheking",
    titulo: "O Senhor dos Anéis: O Retorno do Rei",
    categoria: "filmes",
    imagem: "images/EsdlaIII.jpg",
    sinopse: "Enquanto Frodo e Sam chegam a Mordor para destruir o Um Anel, Aragorn lidera a batalha final contra Sauron.",
    ano: 2003,
    duracao: "3h 21min",
    diretor: "Peter Jackson",
    elenco: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    imdb: 9.0,
    classificacao: "12+",
    genero: "Ação, Aventura, Fantasia",
    episodios: 1
  },
  {
    id: "exorcist",
    titulo: "O Exorcista",
    categoria: "filmes",
    imagem: "images/19873738.webp",
    sinopse: "Uma mãe busca a ajuda de dois padres para salvar sua filha possuída por uma entidade demoníaca.",
    ano: 1973,
    duracao: "2h 2min",
    diretor: "William Friedkin",
    elenco: "Ellen Burstyn, Max von Sydow, Linda Blair",
    imdb: 8.1,
    classificacao: "18+",
    genero: "Terror",
    episodios: 1
  },
  {
    id: "quartetofantastico",
    titulo: "Quarteto Fantástico: Primeiros Passos",
    categoria: "filmes",
    imagem: "images/57e051a8f6184b1a6ea14854e191817c.webp",
    sinopse: "Quatro jovens ganham poderes extraordinários após um experimento científico dar errado, precisando aprender a usar suas habilidades para salvar o mundo.",
    ano: 2015,
    duracao: "1h 40min",
    diretor: "Josh Trank",
    elenco: "Miles Teller, Michael B. Jordan, Kate Mara, Jamie Bell",
    imdb: 4.3,
    classificacao: "12+",
    genero: "Ação, Aventura, Ficção Científica",
    episodios: 1
  },
  {
    id: "missionimpossible8",
    titulo: "Missão: Impossível – Acerto de Contas Parte Dois",
    categoria: "filmes",
    imagem: "images/missao-impossivel-ajuste-de-contas-parte-dois.jpg",
    sinopse: "Ethan Hunt e sua equipe enfrentam as consequências de sua missão anterior, em mais uma corrida contra o tempo para salvar o mundo.",
    ano: 2025,
    duracao: "2h 40min",
    diretor: "Christopher McQuarrie",
    elenco: "Tom Cruise, Hayley Atwell, Rebecca Ferguson",
    imdb: 0.0, // ainda sem nota oficial
    classificacao: "14+",
    genero: "Ação, Suspense",
    episodios: 1
  },
  {
    id: "superman2025",
    titulo: "Superman",
    categoria: "filmes",
    imagem: "images/8664d1b110b95eb32313683f1a655f5f.webp",
    sinopse: "Clark Kent deve conciliar sua herança kryptoniana com sua vida humana enquanto assume o papel de Superman, símbolo de esperança.",
    ano: 2025,
    duracao: "2h 09min",
    diretor: "James Gunn",
    elenco: "David Corenswet, Rachel Brosnahan, Nicholas Hoult",
    imdb: 0.0, // ainda sem nota oficial
    classificacao: "14+",
    genero: "Ação, Aventura, Ficção Científica",
    episodios: 1
  },
  {
    id: "spiderman3",
    titulo: "Homem-Aranha 3",
    categoria: "filmes",
    imagem: "img/aranha3.png",
    sinopse: "Peter Parker enfrenta novos desafios enquanto o simbionte alienígena ameaça corromper sua vida e sua cidade.",
    ano: 2007,
    duracao: "2h 19min",
    diretor: "Sam Raimi",
    elenco: "Tobey Maguire, Kirsten Dunst, James Franco",
    imdb: 6.3,
    classificacao: "12+",
    genero: "Ação, Aventura, Fantasia",
    episodios: 1
  },
  {
    id: "matrix",
    titulo: "Matrix",
    categoria: "filmes",
    imagem: "images/images.jpg",
    sinopse: "Um jovem hacker descobre a verdade sobre sua realidade e se junta a um grupo de rebeldes para libertar a humanidade das máquinas.",
    ano: 1999,
    duracao: "2h 16min",
    diretor: "Lana Wachowski, Lilly Wachowski",
    elenco: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
    imdb: 8.7,
    classificacao: "14+",
    genero: "Ação, Ficção Científica",
    episodios: 1
  },
  {
    id: "demonslayerinfinitycastle",
    titulo: "Demon Slayer: O Castelo Infinito",
    categoria: "animacoes",
    imagem: "images/MV5BMzM3Yzk0OTMtMWQzOC00NjM2LThlOGYtN2IyNTY4NjlmYTI0XkEyXkFqcGc@._V1_.jpg",
    sinopse: "Tanjiro e os Caçadores de Demônios enfrentam Muzan Kibutsuji em uma batalha épica no misterioso Castelo Infinito.",
    ano: 2025,
    duracao: "3 filmes (arco final)",
    diretor: "Haruo Sotozaki",
    elenco: "Natsuki Hanae, Akari Kitō, Hiro Shimono",
    imdb: 0.0, // ainda sem nota oficial
    classificacao: "14+",
    genero: "Ação, Fantasia, Animação",
    episodios: 3
  },
  {
    id: "johnwick4",
    titulo: "John Wick 4: Baba Yaga",
    categoria: "filmes",
    imagem: "images/John_Wick_-_Chapter_4_promotional_poster.jpg",
    sinopse: "John Wick descobre um caminho para derrotar a Alta Cúpula, mas deve enfrentar inimigos poderosos em uma jornada global.",
    ano: 2023,
    duracao: "2h 49min",
    diretor: "Chad Stahelski",
    elenco: "Keanu Reeves, Donnie Yen, Bill Skarsgård",
    imdb: 7.8,
    classificacao: "16+",
    genero: "Ação, Crime, Suspense",
    episodios: 1
  },
  {
    id: "dbsbroly",
    titulo: "Dragon Ball Super: Broly",
    categoria: "animacoes",
    imagem: "img/dgb.png",
    sinopse: "Goku e Vegeta enfrentam Broly, um Saiyajin incrivelmente poderoso com uma história ligada ao passado de seus povos.",
    ano: 2018,
    duracao: "1h 40min",
    diretor: "Tatsuya Nagamine",
    elenco: "Masako Nozawa, Ryō Horikawa, Bin Shimada",
    imdb: 7.8,
    classificacao: "12+",
    genero: "Ação, Animação, Fantasia",
    episodios: 1
  },
  {
    id: "capamerica2",
    titulo: "Capitão América: O Soldado Invernal",
    categoria: "filmes",
    imagem: "images/MV5BMmFjODFhZmItYTljMy00MDlmLWE2ZjAtYzY0Y2ExYTE1NGEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    sinopse: "Steve Rogers enfrenta um inimigo misterioso conhecido como Soldado Invernal, enquanto descobre conspirações dentro da S.H.I.E.L.D.",
    ano: 2014,
    duracao: "2h 16min",
    diretor: "Anthony Russo, Joe Russo",
    elenco: "Chris Evans, Scarlett Johansson, Sebastian Stan",
    imdb: 7.7,
    classificacao: "12+",
    genero: "Ação, Aventura, Ficção Científica",
    episodios: 1
  },
  {
    id: "autoCompadecida",
    titulo: "O Auto da Compadecida",
    categoria: "filmes",
    imagem: "images/O_auto_da_compadecida.jpg",
    sinopse: "As aventuras de João Grilo e Chicó no sertão nordestino, misturando humor, crítica social e religiosidade.",
    ano: 2000,
    duracao: "1h 44min",
    diretor: "Guel Arraes",
    elenco: "Matheus Nachtergaele, Selton Mello, Fernanda Montenegro",
    imdb: 8.8,
    classificacao: "12+",
    genero: "Comédia, Drama, Aventura",
    episodios: 1
  }
];
